### ISSUE TITLE
Link in wiki not working

### ISSUE THREAD

**Issue by MaxBaeten** [rbonghi/roboteq_control#1]
Hi rbonghi

I was trying to test your code but in the wiki the link to http://rnext.it/project/roboteq_control was not working. Can you provide a small readme on how to start your node?

Regards Max

**Comment by rbonghi** [comment]
Webpage http://rnext.it/project/roboteq-controller/
I hope for this weekend to add the basic information.

Raffaello

PS: Next week I will be with my robot [Panther](http://rnext.it/panther) at https://www.gputechconf.eu/
