### ISSUE TITLE
Emergency Stop

### ISSUE THREAD

**Issue by enco77** [rbonghi/roboteq_control#16]
**whenever** publishing false or true to '/roboteq/emergency stop' topic emergency stop turns on
rostopic pub /roboteq/emergency_stop std_msgs/Bool "data: false" -r 10 Publishing like @thingsjimenez  said
code:
````
void Roboteq::stop_Callback(const std_msgs::Bool::ConstPtr& msg)
{
    // Wait end motor loop
    while(motor_loop_);
    // Read status message
    bool status = (bool)msg.get()->data;
    if(status)
    {
        // Send emergency stop
        mSerial->command("EX");
        ROS_WARN_STREAM("Emergency stop");
    } else
    {
        // Safety release
        mSerial->command("MG");
        ROS_WARN_STREAM("Safety release");
    }
}`
```
emergency stop don't release

**Comment by sjimenez44** [comment]
@enco77 The problem with this `rostopic pub /roboteq/emergency_stop std_msgs/Bool "data: false" -r 10`. Because when you release the command in the terminal you only send the same flag, you need to send the command to continue controlling the motors.

**Comment by enco77** [comment]
> @enco77 The problem with this `rostopic pub /roboteq/emergency_stop std_msgs/Bool "data: false" -r 10`. Because when you release the command in the terminal you only send the same flag, you need to send the command to continue controlling the motors.

I don't clearly understand you. Did you mean velocity commands? I control motors using` rosrun teleop_twist_keyboard teleop_twist_keyboard.py `
### But nothing is happen after emergency stop

**Comment by enco77** [comment]
**maybe it's a bug**
```
void Roboteq::stop_Callback(const std_msgs::Bool::ConstPtr& msg)
{
    // Wait end motor loop
    //while(motor_loop_);
    // Read status message
    bool status = (bool)msg.get()->data;
    if(status)
    {
        // Send emergency stop
        mSerial->command("EX");
        ROS_WARN_STREAM("Emergency stop");
    } else
    {
        // Safety release
        mSerial->command("MG");
        ROS_WARN_STREAM("Safety release");
    }
}`
```
```
after commenting while(motor_loop_); it's work
