### ISSUE TITLE
Get SDC2130  working

### ISSUE THREAD

**Issue by freekvh** [rbonghi/roboteq_control#2]
Dear rbonghi,

I also have this controller but I have little experience with the ros_control structure
Can you tell me how do I get from your code to a running controller?
Do you use launch files or service calls? And what are joint names since I've seen a service call to launch controllers from the controller manager but for that I need to know how you named them?

Best regards,

Freek.

**Comment by Herathkumar** [comment]
Hi Freekvh,

I am glad to see you are also working with the same roboteq contoller and ROS pacakge. I treid to implement this package with my dual BLDC motor Roboteq contoller. I am able to buld this ROS pacakge and launch the file. But I am stuck with how to send the command and contol the motor using this ROS pacakage. So I think we can discuss here and find solution together. looking forward  to your reply. Thanks

**Comment by aarontan-git** [comment]
@freekvh @Herathkumar Hello, I am having the same issues, I was wondering if you two have figured it out?

Thank you,
Aaron

**Comment by rbonghi** [comment]
Hi @aarontan-git and @freekvh ,

I apologise if I reply only after 1 YEAR and few months late.
Did you fix this issue? If yes, I can implement your feature on my code

Best,
Raffaello

**Comment by freekvh** [comment]
> 
> 
> Hi @aarontan-git and @freekvh ,
> 
> I apologise if I reply only after 1 YEAR and few months late.
> Did you fix this issue? If yes, I can implement your feature on my code
> 
> Best,
> Raffaello

Hi Raffaello,

We never solved the issue sadly, using the proprietary software that came with the motors we could make them spin and write firmware to them but we never got them to work with ROS, sadly. I hope you can ever make it work, good luck!

**Comment by rbonghi** [comment]
Thank you @freekvh ,

I temporary close this issue, if I found a way to improve the code I will write you a new message just for the future
