### ISSUE TITLE
SBL2360 driver

### ISSUE THREAD

**Issue by AlexisTM** [rbonghi/roboteq_control#3]
Hey, what is the breaking part between the different motor driver versions? (So I can port the SBL2360)

**Comment by HappySamuel** [comment]
Hi @AlexisTM 

I am also using SBL2360, but i couldn't get this work with it. Have you successfully control SBL2360 using this roboteq_control?

Best,
Samuel

**Comment by AlexisTM** [comment]
Dear Samuel, I actually went for another library: https://github.com/umdlife/roboteq forked from https://github.com/g/roboteq

**Comment by rbonghi** [comment]
Hi All,

I'm looking your issue.  In these days I'm working again with my robot Panther and also with the roboteq control.

Which ROS are you working?

**Comment by HappySamuel** [comment]
Hi @AlexisTM 

Thanks for the sharing, I have questions on below:
> Ticks = N_Poles * Hall_Sensor_Number = 8*3 = 24

Ticks = counts/ revolute?
Hall_Sensor_Number, how shall we count?
N_Poles = Number of poles pairs?

Hi @rbonghi 
I am currently working on ROS 1 - Kinetic. Hope can get some guidance from you on controlling roboteq control via ROS.

Best,
Samuel

**Comment by rbonghi** [comment]
Hi all,

I didn't started to fix the issues of my package, but this morning Roboteq release a ROS package

https://www.roboteq.com/index.php/support/setup-troubleshooting-faq/113-support/supportfaq/484-q-how-to-install-and-use-roboteq-s-ros-package

https://github.com/Roboteq-Inc/ROS-Driver

We should check if this repo cover well all our Roboteq controllers

**Comment by AlexisTM** [comment]
I came to say the same as @rbonghi

**Comment by rbonghi** [comment]
The https://github.com/Roboteq-Inc/ROS-Driver is a nice driver, but I was looking does no implement any type of [**ros_control**](http://wiki.ros.org/ros_control) feature.
The https://github.com/Roboteq-Inc/ROS-Driver/blob/master/roboteq_motor_controller_driver/src/diff_odom.cpp implement only an hard coded differiantial drive control.

I think at this time it's better to fix all bugs and make improvements on my package. I will start to work this week 👍 

PS: @griz1112 I add in this loop

**Comment by griz1112** [comment]
I agree. The new driver is very green still haven’t gotten it to work.

Dan

**Comment by rbonghi** [comment]
I made significant updates in these days.
Now this code does not have warning from `dynamic_reconfigure::Server` and I'm fixing #4
I add a new example for a differential drive and rewrite the Readme.
If there are new issues or something not clear keep me posted.

PS: I think I will made a new version of this package for ROS2 soon :-)

**Comment by rbonghi** [comment]
> Thanks for the sharing, I have questions on below:
> 
> > Ticks = N_Poles * Hall_Sensor_Number = 8*3 = 24
> 
> Ticks = counts/ revolute?
> Hall_Sensor_Number, how shall we count?
> N_Poles = Number of poles pairs?

Where did you find this line?
If is mine, I didn't found it! :sweat_smile: 

> Hi @rbonghi
> I am currently working on ROS 1 - Kinetic. Hope can get some guidance from you on controlling roboteq control via ROS.

I made a brand new example to use this package.
[differential_drive.launch](https://github.com/rbonghi/roboteq_control/blob/master/launch/differential_drive.launch)
I didn't test on Kinetic this test, but I think works fine (It's a simple launcher version of my robot)

Anyway If you have issues or something does not work open a new issue :+1:

**Comment by AlexisTM** [comment]
@rbonghi The question was related to: https://github.com/umdlife/roboteq

Ticks = counts/revolution
N_poles = number of poles of the motor (see datasheet)
Hall_Sensor_Number = Number of all sensors, generally 3 (see datasheet)

Note that I do not maintain that library anymore as I am not working at that company anymore.
