### ISSUE TITLE
Timing issue: Access too often to Param Server

### ISSUE THREAD

**Issue by AlexisTM** [rbonghi/roboteq_control#4]
The following reads the ratio whenever called.
It is bad for runtime as it is a blocking networking task. 
Instead, the parameter should be read at the start of the node, also because it is very likely that this value will not change.

https://github.com/rbonghi/roboteq_control/blob/b0406fb79a0b3e9f50dd4c51617b6149262c2493/src/roboteq/motor.cpp#L103-L120

**Comment by rbonghi** [comment]
Gotcha!
I will start to fix soon!

**Comment by rbonghi** [comment]
Hi @AlexisTM,

I know, you don't believe on my message, but I'm fixing this issue! Yes, we are close to easter, the weather is not bad, but maybe will snow today :-D

I move the reduction parameter on Motor initialization. I'm already testing, but look like fine this fix.
https://github.com/rbonghi/roboteq_control/commit/6c59d5d15fe547ac3415c0a4a278bd9649625d2a

I will close this issue for this week, if everything is fine.

**Comment by AlexisTM** [comment]
Definitely better :) 

The issue was extremely clear when having a remote master. With a local master, it is bad practice but still works (as you have something like 40Gb/s bandwidth)
