### ISSUE TITLE
Memory leak from serial_controller

### ISSUE THREAD

**Issue by elhayra** [rbonghi/roboteq_control#5]
Hi, 

It look like you have memory leak. You are declaring new serial controller in roboteq_control.cpp, but I couldn't find a corresponding delete call

**Comment by rbonghi** [comment]
Hi @elhayra 

I apologise if I reply only with 1 YEAR ad few months late, but I was totally on focus in other projects.
I was reading your commits and your improvements in your [fork](https://github.com/robotican/roboteq_control).  I think to merge your parts and fix other stuff, when you want you can open a pull request and I pick up this package.

Keep me posted

**Comment by elhayra** [comment]
Hi @rbonghi , 
I opened a pull request.
