### ISSUE TITLE
Serial COM Or CAN BUS Communication

### ISSUE THREAD

**Issue by David9696** [rbonghi/roboteq_control#8]
Hi,

I am new to Roboteq controller. I come across this package and I think you have done a very good job. May i know how do you control the motor controller in this package? Is it through rs232 or rs485 or can bus?

Hope you can enlighten me.

Thanks.

David

**Comment by rbonghi** [comment]
Hi @David9696 

Thank you! Yes, you are right, I forgot to specify that this package works with the RS232.
You can simply plug the microusb on your roboteq board in your PC and use it.

If you have any issues, don't hesitate to write me.

**Comment by David9696** [comment]
Hi,

Thanks for your quick response. Now I have better idea. Someone told me that the microusb might not be stable when the robot is moving. Is it true?

I have been assigned to work with roboteq controller for my final year project. I have some questions for the emergency switch wiring. Do you mind to share your experience? Could I send email to you for further discussion?

Hope you could enlighten me. Thanks.

David

**Comment by rbonghi** [comment]
> Thanks for your quick response. Now I have better idea. Someone told me that the microusb might not be stable when the robot is moving. Is it true?

I read the same, but my robot never lost the connection to the roboteq board for the cable

> I have been assigned to work with roboteq controller for my final year project. I have some questions for the emergency switch wiring. Do you mind to share your experience? Could I send email to you for further discussion?

The roboteq boards have a emergency pin to wire, but if I remember well was really simple to connect. (I want wire as well soon on mine). There is also a serial message to send to change in emergency mode the roboteq board, and this option is implemented on my ros package.

I have on my joystick a button mapped to emergency switch off the robot, it is really useful.

You can write me on: raffaello@rnext.it

Best,
Raffaello
