### ISSUE TITLE
Gear ratio = 1 even config in roboteq.yaml

### ISSUE THREAD

**Issue by 5730289021-NN** [rbonghi/roboteq_control#9]
Dear  rbonghi,
Thank you for making this awesome package. Most of things worked great. But I have a little problem when using with geared motor which number of gear = 20 when I ran command
`rosparam get` to get the gear ratio, it showed me 1 instead of 20. I've already set at the `ratio: 16.0` inside roboteq.yaml file
I suspected that the dynamic reconfigure might've altered the value. Please guide me if I might've miss some necessary steps

Thank you
Oak

**Comment by rbonghi** [comment]
Hi @5730289021-NN ,

I apologise for my late reply, but I will check the reason, I hope soon.

Meanwhile try to change by the yaml file before the roboteq_control start.

**Comment by 5730289021-NN** [comment]
Thank you for response, I'll try on that

**Comment by balamuruganky** [comment]
@5730289021-NN : Please check the fix available in https://github.com/rbonghi/roboteq_control/pull/11. Change the ratio max range value based on your need. Currently, the range set to 0.0 to 1.0
